# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WYNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for WYNews

 pod 'SDWebImage'
 pod 'AFNetworking'
 pod 'YYModel'
 pod 'Masonry'
 pod 'FMDB'

end
